/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as InvitesIndexRouteImport } from './routes/invites/index'
import { Route as FeatureFlagsIndexRouteImport } from './routes/feature-flags/index'
import { Route as FamiliesIndexRouteImport } from './routes/families/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as FamiliesFamilyIdRouteImport } from './routes/families/$familyId'
import { Route as BillingFamilyIdRouteImport } from './routes/billing/$familyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesIndexRoute = InvitesIndexRouteImport.update({
  id: '/invites/',
  path: '/invites/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsIndexRoute = FeatureFlagsIndexRouteImport.update({
  id: '/feature-flags/',
  path: '/feature-flags/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesFamilyIdRoute = FamiliesFamilyIdRouteImport.update({
  id: '/families/$familyId',
  path: '/families/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingFamilyIdRoute = BillingFamilyIdRouteImport.update({
  id: '/billing/$familyId',
  path: '/billing/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/billing/$familyId': typeof BillingFamilyIdRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/invites/': typeof InvitesIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/billing/$familyId': typeof BillingFamilyIdRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/audit': typeof AuditIndexRoute
  '/billing': typeof BillingIndexRoute
  '/families': typeof FamiliesIndexRoute
  '/feature-flags': typeof FeatureFlagsIndexRoute
  '/invites': typeof InvitesIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/billing/$familyId': typeof BillingFamilyIdRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/invites/': typeof InvitesIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/billing/$familyId'
    | '/families/$familyId'
    | '/users/$userId'
    | '/analytics/'
    | '/audit/'
    | '/billing/'
    | '/families/'
    | '/feature-flags/'
    | '/invites/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/billing/$familyId'
    | '/families/$familyId'
    | '/users/$userId'
    | '/analytics'
    | '/audit'
    | '/billing'
    | '/families'
    | '/feature-flags'
    | '/invites'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/billing/$familyId'
    | '/families/$familyId'
    | '/users/$userId'
    | '/analytics/'
    | '/audit/'
    | '/billing/'
    | '/families/'
    | '/feature-flags/'
    | '/invites/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  BillingFamilyIdRoute: typeof BillingFamilyIdRoute
  FamiliesFamilyIdRoute: typeof FamiliesFamilyIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  BillingIndexRoute: typeof BillingIndexRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  FeatureFlagsIndexRoute: typeof FeatureFlagsIndexRoute
  InvitesIndexRoute: typeof InvitesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/': {
      id: '/invites/'
      path: '/invites'
      fullPath: '/invites/'
      preLoaderRoute: typeof InvitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags/': {
      id: '/feature-flags/'
      path: '/feature-flags'
      fullPath: '/feature-flags/'
      preLoaderRoute: typeof FeatureFlagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$familyId': {
      id: '/families/$familyId'
      path: '/families/$familyId'
      fullPath: '/families/$familyId'
      preLoaderRoute: typeof FamiliesFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/$familyId': {
      id: '/billing/$familyId'
      path: '/billing/$familyId'
      fullPath: '/billing/$familyId'
      preLoaderRoute: typeof BillingFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  BillingFamilyIdRoute: BillingFamilyIdRoute,
  FamiliesFamilyIdRoute: FamiliesFamilyIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  BillingIndexRoute: BillingIndexRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  FeatureFlagsIndexRoute: FeatureFlagsIndexRoute,
  InvitesIndexRoute: InvitesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
