import type { IncomeEntry, IncomeType } from '@family/types'
import { getSupabaseClient } from './client'

function rowToEntry(row: {
  id: string
  family_id: string
  person_id: string | null
  type: string | null
  amount: number
  date: string
  description: string | null
  auto_generated: boolean
  recurring_transaction_id: string | null
  created_at: string
}): IncomeEntry {
  return {
    id: row.id,
    familyId: row.family_id,
    personId: row.person_id,
    type: (row.type as IncomeType) ?? null,
    amount: row.amount,
    date: row.date,
    description: row.description ?? undefined,
    autoGenerated: row.auto_generated,
    recurringTransactionId: row.recurring_transaction_id,
    createdAt: new Date(row.created_at),
  }
}

export async function fetchIncomeEntries(
  familyId: string,
  year: number,
  month?: number,
): Promise<IncomeEntry[]> {
  const supabase = getSupabaseClient()

  let gte = `${year}-01-01`
  let lt = `${year + 1}-01-01`

  if (month !== undefined) {
    gte = `${year}-${String(month).padStart(2, '0')}-01`
    lt =
      month === 12
        ? `${year + 1}-01-01`
        : `${year}-${String(month + 1).padStart(2, '0')}-01`
  }

  const { data, error } = await supabase
    .from('income_entries')
    .select('id, family_id, person_id, type, amount, date, description, auto_generated, recurring_transaction_id, created_at')
    .eq('family_id', familyId)
    .gte('date', gte)
    .lt('date', lt)
    .order('date', { ascending: false })

  if (error) throw error
  return data.map(rowToEntry)
}

export async function createIncomeEntry(input: {
  familyId: string
  personId?: string | null
  type?: IncomeType | null
  amount: number
  date: string
  description?: string
  autoGenerated?: boolean
  recurringTransactionId?: string | null
}): Promise<IncomeEntry> {
  const supabase = getSupabaseClient()
  const { data, error } = await supabase
    .from('income_entries')
    .insert({
      family_id: input.familyId,
      person_id: input.personId ?? null,
      type: input.type ?? null,
      amount: input.amount,
      date: input.date,
      description: input.description ?? null,
      auto_generated: input.autoGenerated ?? false,
      recurring_transaction_id: input.recurringTransactionId ?? null,
    })
    .select('id, family_id, person_id, type, amount, date, description, auto_generated, recurring_transaction_id, created_at')
    .single()

  if (error) throw error
  return rowToEntry(data)
}

export async function updateIncomeEntry(
  id: string,
  input: Partial<{ personId: string | null; type: IncomeType | null; amount: number; date: string; description: string | null }>,
): Promise<IncomeEntry> {
  const update: Record<string, unknown> = {}
  if ('personId' in input) update.person_id = input.personId
  if ('type' in input) update.type = input.type
  if (input.amount !== undefined) update.amount = input.amount
  if (input.date !== undefined) update.date = input.date
  if ('description' in input) update.description = input.description

  const supabase = getSupabaseClient()
  const { data, error } = await supabase
    .from('income_entries')
    .update(update)
    .eq('id', id)
    .select('id, family_id, person_id, type, amount, date, description, auto_generated, recurring_transaction_id, created_at')
    .single()

  if (error) throw error
  return rowToEntry(data)
}

export async function deleteIncomeEntry(id: string): Promise<void> {
  const supabase = getSupabaseClient()
  const { error } = await supabase.from('income_entries').delete().eq('id', id)
  if (error) throw error
}
