import { useState } from 'react'
import { CalendarClock } from 'lucide-react'
import { toast } from 'sonner'
import { createExpense, createIncomeEntry, updateRecurringTransaction } from '@family/supabase'
import type { CatchUpItem } from '#/lib/recurringExpenses'
import { nextOccurrence } from '#/lib/recurringExpenses'
import { Button } from '#/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '#/components/ui/dialog'
import { formatCurrency } from '#/lib/utils'

type Props = {
  familyId: string
  items: CatchUpItem[]
  open: boolean
  onOpenChange: (open: boolean) => void
  onDone: () => void
}

async function generateEntry(
  familyId: string,
  item: CatchUpItem['recurring'],
  date: string,
): Promise<void> {
  if (item.direction === 'expense') {
    await createExpense({
      familyId,
      amount: item.amount,
      date,
      description: item.description,
      categoryId: item.categoryId,
      locationId: item.locationId,
      paidById: item.paidById,
      autoGenerated: true,
      recurringTransactionId: item.id,
    })
  } else {
    await createIncomeEntry({
      familyId,
      amount: item.amount,
      date,
      description: item.description,
      personId: item.personId,
      type: item.incomeType,
      autoGenerated: true,
      recurringTransactionId: item.id,
    })
  }
}

export function CatchUpDialog({ familyId, items, open, onOpenChange, onDone }: Props) {
  const [isPending, setIsPending] = useState(false)

  async function generateAll() {
    setIsPending(true)
    try {
      for (const { recurring, missedDates } of items) {
        await Promise.all(missedDates.map((date) => generateEntry(familyId, recurring, date)))
        const lastDate = missedDates[missedDates.length - 1]
        await updateRecurringTransaction(recurring.id, {
          nextDueDate: nextOccurrence(lastDate, recurring.frequency),
        })
      }
      const total = items.reduce((n, i) => n + i.missedDates.length, 0)
      toast.success(`Generated ${total} backdated entries`)
      onDone()
      onOpenChange(false)
    } catch {
      toast.error('Failed to generate entries')
    } finally {
      setIsPending(false)
    }
  }

  async function generateLatestOnly() {
    setIsPending(true)
    try {
      for (const { recurring, missedDates } of items) {
        const latestDate = missedDates[missedDates.length - 1]
        await generateEntry(familyId, recurring, latestDate)
        await updateRecurringTransaction(recurring.id, {
          nextDueDate: nextOccurrence(latestDate, recurring.frequency),
        })
      }
      toast.success(
        `Generated ${items.length} entr${items.length !== 1 ? 'ies' : 'y'} (latest only)`,
      )
      onDone()
      onOpenChange(false)
    } catch {
      toast.error('Failed to generate entries')
    } finally {
      setIsPending(false)
    }
  }

  async function skipAll() {
    setIsPending(true)
    try {
      for (const { recurring, missedDates } of items) {
        const lastDate = missedDates[missedDates.length - 1]
        await updateRecurringTransaction(recurring.id, {
          nextDueDate: nextOccurrence(lastDate, recurring.frequency),
        })
      }
      onOpenChange(false)
    } catch {
      toast.error('Failed to skip')
    } finally {
      setIsPending(false)
    }
  }

  const totalMissed = items.reduce((n, i) => n + i.missedDates.length, 0)

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <CalendarClock className="h-5 w-5 text-amber-500" />
            <DialogTitle>Missed recurring entries</DialogTitle>
          </div>
          <DialogDescription>
            {items.length === 1
              ? `"${items[0].recurring.description}" missed ${totalMissed} occurrence${totalMissed !== 1 ? 's' : ''}.`
              : `${items.length} recurring transactions missed a total of ${totalMissed} occurrences.`}{' '}
            What would you like to do?
          </DialogDescription>
        </DialogHeader>

        <ul className="space-y-1.5 max-h-48 overflow-y-auto">
          {items.map(({ recurring, missedDates }) => (
            <li
              key={recurring.id}
              className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"
            >
              <div className="min-w-0 flex-1">
                <span className="font-medium truncate block">{recurring.description}</span>
                <span className="text-xs text-muted-foreground capitalize">{recurring.direction}</span>
              </div>
              <span className="text-muted-foreground ml-2 shrink-0">
                {formatCurrency(recurring.amount)} × {missedDates.length} missed
              </span>
            </li>
          ))}
        </ul>

        <DialogFooter className="flex-col gap-2 sm:flex-col">
          <Button onClick={generateAll} disabled={isPending} className="w-full">
            Generate all ({totalMissed} backdated entries)
          </Button>
          <Button
            onClick={generateLatestOnly}
            disabled={isPending}
            variant="outline"
            className="w-full"
          >
            Generate latest only ({items.length} entr{items.length !== 1 ? 'ies' : 'y'})
          </Button>
          <Button
            onClick={skipAll}
            disabled={isPending}
            variant="ghost"
            className="w-full text-muted-foreground"
          >
            Skip — start fresh from next due date
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
